---
- hosts: intranet
  become: yes
  vars_files:
    - vars/default.yml
  tasks:
    - name: "Instalação de Pacotes Web"
      apt:
        pkg:
          - php7.0
          - php-pear
          - php7.0-curl
          - php7.0-gd
          - php7.0-intl
          - php7.0-xmlrpc
          - php7.0-mysql
          - apache2
          - python-mysqldb
          - wget
          - zip
          - unzip
          - curl
          - vim
        state: present
        update_cache: yes
    - name: "Diretorio do Webserver"
      file:
        path: /srv/www
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'
      
    - name: "Download e Extração do conteudo da aplicação"      
      unarchive:
        src: https://github.com/rogerramossilva/devops/raw/master/express.zip
        dest: /srv/www
        remote_src: yes
        validate_certs: no
    - name: "Substituindo IP de Conexão com o Banco de dados"
      replace:
        path: /srv/www/express/backup.php
        regexp: '192\.168\.1\.20'
        replace: '192.168.1.102'
    - name: "Criando o arquivo do Vhost o apache"
      template:
        src: "files/express.conf"
        dest: "/etc/apache2/sites-available/{{ http_conf}}"
    - name: "Criando o Directory para controle das configurações do servidor Apache"
      template:
        src: "files/direxpress.conf"
        dest: "/etc/apache2/conf-available/direxpress.conf"
    - name: "Alterando arquivo hosts"
      template:
        src: files/hostsintranet
        dest: /etc/hosts

    - name: "Habilitando o Site"
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: restart apache

    - name: "Habilitando o direxpress"
      shell: /usr/sbin/a2enconf direxpress.conf
      notify: restart apache
    - name: "Habilitando modulo virtual hosts"
      apache2_module:
        name: "{{ item }}"
        state: present
      loop:
        - vhost_alias
        - php7.0
      notify: restart apache
    - name: "Adequando Permissionamento novamente"
      file:
        path: /srv/www/express
        state: directory
        recurse: yes
        owner: "{{ app_user }}"
        group: "{{ app_user }}"


  handlers:
    - name: 'restart apache'
      service:
        name: apache2
        state: restarted
        enabled: yes
